// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdz6mEZ1MgN03jT1hRZsIo2A52tnob2jE',
    appId: '1:250476651920:web:8cdd7f05cb2ac2ac94ff15',
    messagingSenderId: '250476651920',
    projectId: 'sellkroindia-677a3',
    authDomain: 'sellkroindia-677a3.firebaseapp.com',
    storageBucket: 'sellkroindia-677a3.appspot.com',
    measurementId: 'G-C2M9TJ3ZPF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2nkhp_d_YDnfmI75FguNPkMMuyx8j0og',
    appId: '1:250476651920:android:107e476027b7dd0694ff15',
    messagingSenderId: '250476651920',
    projectId: 'sellkroindia-677a3',
    storageBucket: 'sellkroindia-677a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyaCe9CRs_zlD3Yj74buECbICPIAdU38Y',
    appId: '1:250476651920:ios:288627afec3af7de94ff15',
    messagingSenderId: '250476651920',
    projectId: 'sellkroindia-677a3',
    storageBucket: 'sellkroindia-677a3.appspot.com',
    iosBundleId: 'com.example.skl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyaCe9CRs_zlD3Yj74buECbICPIAdU38Y',
    appId: '1:250476651920:ios:2cec4b6cd0d01cd894ff15',
    messagingSenderId: '250476651920',
    projectId: 'sellkroindia-677a3',
    storageBucket: 'sellkroindia-677a3.appspot.com',
    iosBundleId: 'com.example.skl.RunnerTests',
  );
}
